### ISSUE TITLE
[Dev Issue]The `theme` parameter in the request of `handleTeamsMessagingExtensionConfigurationQuerySettingUrl` is missing?

### ISSUE THREAD

**Issue by kafka-yu** [OfficeDev/BotBuilder-MicrosoftTeams#246] opened 2020-08-07 02:15 UTC
Hi Team,

Recently we found that:
The `theme` parameter in the request of `handleTeamsMessagingExtensionConfigurationQuerySettingUrl` is missing.

As we know, it is existing before. Is this a new change for Teams?

Thanks!

**Comment by Gousia-MSFT** [comment] 2020-08-07 06:09
Duplicate of https://github.com/MicrosoftDocs/msteams-docs/issues/1957.

**Closed by Gousia-MSFT** 2020-08-07 06:09 UTC
Labels: duplicate
